version: "3.9"
services:

  bison_task:
    build:
      context: ./.
      target: task
    environment:
      - TASK_APP=bison.task.test_task
    env_file:
      ./.env.task.conf
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: bison_task
        awslogs-stream: test_task
    volumes:
      # bind mount from host machine
      - "/home/ubuntu/aws_data:/volumes/bison_data"
      # volumes
      - "scratch-path:/scratch-path"

volumes:
  scratch-path:
