version: "3.9"
services:

  bison:
    build:
      context: ./.
      target: flask
    networks:
      - nginx
    environment:
      - FLASK_APP=flask_app.bison.routes:app
    env_file:
      ./.env.conf
    restart: unless-stopped
    volumes:
      # volumes
      - "scratch-path:/scratch-path"
      - "webpack-output:/volumes/webpack-output"
      - "static-files:/home/bison/bison/frontend/static"


  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - bison

    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "static-files:/volumes/static-files:ro"
      - "webpack-output:/volumes/webpack-output:ro"
      # bind mounts from host machine
      - "/etc/letsencrypt:/etc/letsencrypt:ro"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./bison/frontend/static/:/var/www/:ro"

#  front-end:
#    build:
#      context: ./.
#      target: front-end
#    volumes:
#      - "webpack-output:/home/node/dist"

volumes:
  scratch-path:
  static-files:
  webpack-output:

networks:
  nginx:
