name: Sphinx to GitHub Pages
# Builds documentation residing at https://biotaphy.github.io/tutorials/
on:
  push:
    tags:
      - '*.*.*' # Tag events matching {major}.{minor}.{patch}{whatever}
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Install dependencies
        run: pip install sphinx sphinx_rtd_theme myst_parser
      - name: Sphinx build
        run: sphinx-build _sphinx_config _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true

#    steps:
#    - name: Checkout
#      uses: actions/checkout@master
#      with:
#        fetch-depth: 0
#    - name: Install documentation dependencies
#      #uses: py-actions/py-dependency-install@v2
#      #with:
#      #  path: "requirements-docs.txt"
#      run: |
#        pip install -r requirements-docs.txt
#    - name: Build and Commit
#      uses: sphinx-notes/pages@2.0
#      with:
#        documentation_path: _sphinx_config/
#    - name: Push changes to GH Pages branch
#      uses: ad-m/github-push-action@master
#      with:
#        github_token: ${{ secrets.GITHUB_TOKEN }}
#        branch: gh-pages
